### ISSUE TITLE
Keyboard Input [estimated: 1]

### ISSUE THREAD

**Issue by ekrebs5** [HPI-SWA-Teaching/SWT17-Project-13#29]
As a SWA student I want to be able to use keyboard input in order to make my game objects (morphs) react to keyboard input.

Acceptance:
- [x] I want a function "isKeyPressed:" which I can call in my step function
- [x] I want it operating system independent
- [x] I want a documentation/example (in form of a test) of important possible keys (letters, numbers, arrows, shift, tab)
- [x] documentation or class comment to show which keys are supported and how (characters) they are adressed

**Comment by arthurz0** [comment]
it seems like there is no Character shift

**Comment by ekrebs5** [comment]
os were not specified for this, but from now on: features should work on mac, windows and linux

documentation of key values is in initializeKeyLookup[...] of GmKeyHandler

**Comment by ekrebs5** [comment]
not accepted, errors thrown

**Comment by ben243871694** [comment]
+ make sure that functionality is the same for each OS
